
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="bg-white border-t border-gray-200 mt-12">
      <div className="max-w-5xl mx-auto py-6 px-4 sm:px-6 lg:px-8 text-center text-sm text-gray-500">
        <p>&copy; {new Date().getFullYear()} Landry's Log. All rights reserved.</p>
        <p className="mt-1">Content and images generated by Google Gemini.</p>
      </div>
    </footer>
  );
};

export default Footer;
